In [4]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
import io

In [22]:
data = """รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
64003,,,Male,Science,3.67,175.0,,25.0,2024-01-13
64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.0,168.0,70.0,10.0,2023-12-30
64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
64007,กิตติ,21.0,หญิง,วิศวกรรม,4.5,158.0,48.0,35.0,2024-01-05
64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
64011,ธีระ,,,,3.78,,68.0,,2024-01-07
64012,นภา,22.0,ชาย,วิทย์,,171.0,,16.0,2023-12-26
64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
64018,ยุพา,21.0,หญิง,,3.23,161.0,50.0,27.0,2024-01-08
64019,รัตนา,,ชาย,ศิลปศาสตร์,,174.0,76.0,,2023-12-18
64020,ลัดดา,22.0,,Science,3.45,168.0,64.0,23.0,2024-01-06"""

In [23]:
data_io = io.StringIO(data)
df = pd.read_csv(data_io)

In [24]:
print(df.head)

<bound method NDFrame.head of     รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06  >

In [30]:


# แสดงข้อมูลก่อนเติมค่า
print("ก่อนเติมค่า")
print(df)
# เติมชื่อ
df.loc[df["รหัสนักศึกษา"] == 64003, "ชื่อ"] = "โอนาน่า"

# เติมคณะ
df.loc[df["รหัสนักศึกษา"] == 64011, "คณะ"] = "วิทยาศาสตร์"
df.loc[df["รหัสนักศึกษา"] == 64018, "คณะ"] = "ศิลปศาสตร์"

# เติมเพศที่หาย (จากชื่อ)
df.loc[df["รหัสนักศึกษา"] == 64020, "เพศ"] = "ชาย"

df.loc[df["รหัสนักศึกษา"] == 64011,"ส่วนสูง_cm"]="199.99"
df.loc[df["รหัสนักศึกษา"] == 64011,"ชั่วโมงเรียน_ต่อสัปดาห์"]="10.0"

df.loc[df["รหัสนักศึกษา"] == 64003,"น้ำหนัก_kg"]="65.5"

df.loc[df["รหัสนักศึกษา"] == 64012,"น้ำหนัก_kg"]="75.55"
df.loc[df["รหัสนักศึกษา"] == 64019,"ชั่วโมงเรียน_ต่อสัปดาห์"]="25.25"
# เหมาะกับข้อมูลตัวเลข - ใช้ค่าเฉลี่ย
mean_age = df['อายุ'].mean()
df['อายุ'].fillna(mean_age, inplace=True)

print(f"\nค่าเฉลี่ยอายุ - {mean_age:.1f} ปี")
print("หลังเติมค่า")
print(df)

ก่อนเติมค่า
    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003    โอนานา   28.470588    Male         Science  3.67
3          64004  สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006     กานต์  150.000000     ชาย     Engineering  3.12
6          64007     กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000       M            Arts  3.34
9          64010      ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011      ธีระ   28.470588     NaN     วิทยาศาสตร์  3.78
11         64012       นภา   22.000000     ชาย           วิทย์   NaN
12         64013     บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014     ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015     พิมพ์   22.000000  Female             Sci  3.67
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000     ชาย         Science  3.45

   ส่วนสูง_cm น้ำหนัก_kg ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0       170.0       65.0                    15.0      2024-01-23
1       165.0       58.0                    20.0      2024-02-05
2       175.0       65.5                    25.0      2024-01-13
3       168.0       70.0                    10.0      2023-12-30
4       160.0       52.0                    30.0      2024-01-27
5       172.0       75.0                    12.0      2023-12-23
6       158.0       48.0                    35.0      2024-01-05
7       180.0       82.0                    18.0      2024-01-23
8       163.0       55.0                    22.0      2024-02-11
9       167.0       60.0                    28.0      2024-01-03
10     199.99       68.0                    10.0      2024-01-07
11      171.0      75.55                    16.0      2023-12-26
12      169.0       72.0                    24.0      2023-12-26
13      164.0       54.0                    19.0      2024-01-08
14      162.0       56.0                    26.0      2024-02-06
15      173.0       78.0                    14.0      2024-01-20
16      166.0       62.0                    21.0      2024-01-24
17      161.0       50.0                    27.0      2024-01-08
18      174.0       76.0                   25.25      2023-12-18
19      168.0       64.0                    23.0      2024-01-06

ค่าเฉลี่ยอายุ - 28.5 ปี
หลังเติมค่า
    รหัสนักศึกษา      ชื่อ        อายุ     เพศ             คณะ   GPA  \
0          64001     สมชาย   20.000000     ชาย     วิทยาศาสตร์  3.21
1          64002    สมหญิง   21.000000    หญิง           วิทย์  3.45
2          64003   โอนาน่า   28.470588    Male         Science  3.67
3          64004  สมศักดิ์   22.000000       ช  คณะวิทยาศาสตร์ -1.00
4          64005      สมใจ   19.000000       ญ           วิศวะ  3.89
5          64006     กานต์  150.000000     ชาย     Engineering  3.12
6          64007     กิตติ   21.000000    หญิง        วิศวกรรม  4.50
7          64008      จิรา   20.000000       F      ศิลปศาสตร์  2.98
8          64009    ชนาธิป   23.000000       M            Arts  3.34
9          64010      ดารา   21.000000    หญิง           ศิลป์  3.56
10         64011      ธีระ   28.470588     NaN     วิทยาศาสตร์  3.78
11         64012       นภา   22.000000     ชาย           วิทย์   NaN
12         64013     บุญมี   20.000000    หญิง           วิศวฯ  3.23
13         64014     ปรีชา   21.000000     ชาย    Liberal Arts  3.45
14         64015     พิมพ์   22.000000  Female             Sci  3.67
15         64016      ภูมิ   19.000000       ช     วิทยาศาสตร์  3.89
16         64017      มานี   20.000000       ญ  วิศวกรรมศาสตร์  3.01
17         64018      ยุพา   21.000000    หญิง      ศิลปศาสตร์  3.23
18         64019     รัตนา   28.470588     ชาย      ศิลปศาสตร์   NaN
19         64020     ลัดดา   22.000000     ชาย         Science  3.45

   ส่วนสูง_cm น้ำหนัก_kg ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0       170.0       65.0                    15.0      2024-01-23
1       165.0       58.0                    20.0      2024-02-05
2       175.0       65.5                    25.0      2024-01-13
3       168.0       70.0                    10.0      2023-12-30
4       160.0       52.0                    30.0      2024-01-27
5       172.0       75.0                    12.0      2023-12-23
6       158.0       48.0                    35.0      2024-01-05
7       180.0       82.0                    18.0      2024-01-23
8       163.0       55.0                    22.0      2024-02-11
9       167.0       60.0                    28.0      2024-01-03
10     199.99       68.0                    10.0      2024-01-07
11      171.0      75.55                    16.0      2023-12-26
12      169.0       72.0                    24.0      2023-12-26
13      164.0       54.0                    19.0      2024-01-08
14      162.0       56.0                    26.0      2024-02-06
15      173.0       78.0                    14.0      2024-01-20
16      166.0       62.0                    21.0      2024-01-24
17      161.0       50.0                    27.0      2024-01-08
18      174.0       76.0                   25.25      2023-12-18
19      168.0       64.0                    23.0      2024-01-06

/tmp/ipython-input-1660349038.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['อายุ'].fillna(mean_age, inplace=True)